### PR TITLE
Assignment solution

### PR DESCRIPTION
**Pull request by markalfred**
Hi all, this took me about 3.5 hours so I'm pushing it up as it currently is. I would add some more tests and fix up the typography to match the designs, but I figure this is a decent enough example. Let me know if you have any questions about any design decisions I made. Thanks for letting me take part in this exercise!

image

### CODE REVIEW

**Comment by dbaq** [comment]
Thanks, @markalfred, the team will take a look at it on Monday! Have a great weekend!

**Comment by dbaq** [comment]
hey @markalfred, yea that you'd be ideal please :D

**Comment by markalfred** [comment]
@dbaq Prior to me force-pushing, could you re-open this PR? I'm pretty sure Github will ignore the changes unless this is open.

**Comment by dbaq** [comment]
@markalfred good call. it is re-open.

**Pull request closed without merging**
